import { nowISO } from '../../utils/dates';
import type { AppSettings } from './settingsTypes';

export function createDefaultSettings(): AppSettings {
  const timestamp = nowISO();

  return {
    id: 'default',
    colorTheme: 'slate-sky' as const,
    pinEnabled: false,
    pinHash: null,
    pinUpdatedAt: null,
    workday: {
      startTime: '09:00',
      endTime: '18:30',
      primaryRestWindow: {
        enabled: true,
        label: 'מנוחה / איפוס אנרגיה',
        startTime: '14:00',
        endTime: '15:00',
      },
      secondaryRestWindow: {
        enabled: false,
        label: 'הפסקה קצרה',
        startTime: '17:00',
        endTime: '17:20',
      },
    },
    location: {
      label: 'תל אביב',
      city: 'Tel Aviv',
      country: 'Israel',
      timezone: 'Asia/Jerusalem',
      latitude: null,
      longitude: null,
    },
    scheduling: {
      warnOnRestWindowConflict: true,
      autoAddRecurringToToday: false,
    },
    backup: {
      autoBackupEnabled: true,
      backupIntervalMinutes: 30,
      lastBackupAt: null,
      lastSnapshotAt: null,
      fileBackupEnabled: false,
    },
    morningBriefing: {
      nickname: 'מיקי',
      motivationLine: 'לא צריך לנצח את כל היום בבת אחת, רק את הצעד הראשון.',
      closingLine: 'יום נקי, מיקי. מתחילים.',
      style: 'big_brother',
      includeExerciseReminder: true,
      exerciseLine: 'קום, תעשה תרגיל בוקר קצר, ותכניס אנרגיה לגוף לפני המסך.',
      includeGreeting: true,
      includeSummary: true,
      includeDate: true,
      includeWeather: true,
      includeMotivation: true,
      includeReminders: true,
      includeTopTasks: true,
      includeLeads: true,
      includeClosing: true,
      sectionOrder: ['greeting', 'weather', 'topTasks', 'reminders', 'closing'],
      alarmTime: '07:00',
      ringtoneUrl: '',
      androidPublishEndpoint: '/api/morning-briefing',
      androidPublishToken: '',
      lastPublishedAt: null,
    },
    voice: {
      engine: 'browser',
      elevenLabsApiKey: '',
      elevenLabsVoiceId: '',
      elevenLabsModelId: 'eleven_v3',
      elevenLabsOutputFormat: 'mp3_44100_128',
      elevenLabsProxyUrl: '',
      stability: 0.45,
      similarityBoost: 0.82,
      style: 0.2,
      useSpeakerBoost: true,
      speechRate: 0.86,
      narratorGender: 'female',
    },
    socialConnections: {
      linkedin: {
        enabled: false,
        profileUrl: '',
        accessTokenPlaceholder: '',
        lastCheckedAt: null,
      },
      instagram: {
        enabled: false,
        username: '',
        accessTokenPlaceholder: '',
        lastCheckedAt: null,
      },
    },
    shopify: {
      shopDomain: '',
      adminAccessToken: '',
    },
    googleAnalytics: {
      propertyId: '',
    },
    pushSubscriptions: [],
    projects: [
      { id: 'timeraligner', name: 'TimerAligner', colorLabel: 'blue', isActive: true },
      { id: 'alignersworld', name: 'AlignersWorld', colorLabel: 'green', isActive: true },
      { id: 'typeswitch', name: 'TypeSwitch', colorLabel: 'purple', isActive: true },
      { id: 'mission-control', name: 'Mission Control', colorLabel: 'slate', isActive: true },
      { id: 'personal', name: 'Personal', colorLabel: 'amber', isActive: true },
      { id: 'finance', name: 'Finance', colorLabel: 'emerald', isActive: true },
    ],
    domains: [
      { id: 'sales', name: 'Sales', isActive: true },
      { id: 'marketing', name: 'Marketing', isActive: true },
      { id: 'development', name: 'Development', isActive: true },
      { id: 'operations', name: 'Operations', isActive: true },
      { id: 'finance', name: 'Finance', isActive: true },
      { id: 'website-qa', name: 'Website QA', isActive: true },
      { id: 'shopify', name: 'Shopify', isActive: true },
      { id: 'apollo', name: 'Apollo', isActive: true },
      { id: 'production', name: 'Production', isActive: true },
      { id: 'personal', name: 'Personal', isActive: true },
    ],
    createdAt: timestamp,
    updatedAt: timestamp,
  };
}
